### ISSUE TITLE
Method call and returning error "Assertion after the final `assert.async` was resolved"

### ISSUE THREAD

**Issue by settysreekanth** [jquery/qunit#777]
Hi, I am trying to test javascript method as below,

```js
var	spyPostRender = sinon.spy(proxy, "postRender");
var done = assert.async();
proxy.init();
done();
assert.ok(spyPostRender.calledOnce, "postRender() function was called.");
```

where `init()` internally calls an ajax service, however when I do this, I am getting below error. Can anybody help me in resolving this issue?

```
Assertion after the final `assert.async` was resolved@ 85 ms
Source: 	
    at Object.QUnit.assert.Assert.ok (http://code.jquery.com/qunit/qunit-1.17.1.js:1296:8)
```

FYI - I am using QUnit-1.17.1

Thanks in advance

**Comment by settysreekanth** [comment]
@jzaefferer  any suggestions from your side? thanks in advance...

**Comment by JamesMGreene** [comment]
**Two notes:**
 1. That behavior by design (see #668 and #669 for discussion), though it still needs to be added to the documentation (see https://github.com/jquery/api.qunitjs.com/issues/91).
 2. You are not using this correctly. The `done` callback needs to be invoked _only_ after whatever asynchronous operation it is being used for has actually resolved (not just throwing it on the next line).

Your test would probably end up looking more like this:

```js
var spyPostRender = sinon.spy(proxy, "postRender");
var done = assert.async();
proxy.init(function() {
  // Do your real assertions BEFORE invoking the final (i.e. you may have multiple) `done` callback
  assert.ok(spyPostRender.calledOnce, "postRender() function was called.");

  // The final `done` callback MUST be called AFTER all real assertions have been made
  done();
});
```

Or else perhaps use a `sinon.stub` to override `proxy.postRender` to perform your async assertions:

```js
var done = assert.async();

var _postRender = proxy.postRender;
var stubPostRender = sinon.stub(proxy, "postRender", function() {
  var result = _postRender.apply(this, arguments);

    // Do your real assertions BEFORE invoking the final (i.e. you may have multiple) `done` callback
  assert.ok(stubPostRender.calledOnce, "postRender() function was called.");

  // The final `done` callback MUST be called AFTER all real assertions have been made
  done();

  return result;
});

proxy.init();
```

**Comment by settysreekanth** [comment]
@JamesMGreene I am new to QUnit framework so I was not fully aware of Assert.async() api usage. Thanks for your response.
