### ISSUE TITLE
Testing Maps/Sets with QUnit

### ISSUE THREAD

**Issue by godchuanz** [jquery/qunit#833]
Most browsers already implement ES6 Map/Set to some degree. Right now, we have the strange issue of:

        obj1 = new Map(); obj1.set(1,2);
        obj2 = new Map(); obj2.set(3,4);
        assert.deepEqual(obj1, obj2);    // passed

I understand QUnit is not meant to process ES6 Map/Set or iterables yet, but as browsers continue to implement ES6 features, this can actually become a real problem.

**Comment by leobalter** [comment]
on [Weak]{Map,Set}, list items doesn't become properties of the collection instantiated object.

deepEqual checks for the values equality of 2 objects' own and extended (prototype) properties. 

so `assert.deepEqual(obj1, obj2);` will indeed pass.

What we need is not break `deepEqual`, but **maybe extend QUnit to compare ES6 collections**. This should regard it's impossible to compare WeakMap and WeakSet collections if you don't know what they in their collection as they doesn't have a `size` or `forEach` methods and [can't be cast to an Array](http://jsbin.com/datalapavo/edit?js,output).

This leads to another topics: 

- should a assertion to compare ES6 collections be shipped with QUnit or should it come as a plugin?
- we can improve our diff on fails to specify JS native collections instead of just `{}`.

**Comment by godchuanz** [comment]
The way I see it, `deepEqual` should be extended to cater for ES6 Set and Map.From the src, it already specially catered for "array" objects. What needs to be done is to update the code in `equiv()` for "arrays" to use `forEach()`, and for Set/Map to be classified under that switch case. For better code clarity, "arrays" could be renamed "collections" or something.

**Comment by jzaefferer** [comment]
Extending `equiv()` to support `Map` and `Set` seems fine, as long as that is backwards compatible. @godchuanz could you look into putting a patch together for that, and send it as a pull request?

As for WeakMap and WeakSet: If those are uncomparable, we could either consider them unequal or throw an exception. Seems like a separate issue.

For both it might be good to see if other frameworks already implement support for any of these new types. Maybe we can just use their approach.

**Comment by godchuanz** [comment]
Hi, yes. I think I have gotten something together. Can you add me as a collaborator so I can make a pull request?

**Comment by leobalter** [comment]
You can open a PR without being a collaborator, just push to your fork.

**Comment by godchuanz** [comment]
Ok done that. Sorry, not used to forking (still noob to github, especially for jQuery). Hopefully the CLA check and CI passes soon.

**Comment by godchuanz** [comment]
Hi, I've made a pull request but somehow the CI and CLA check are both failing. Can anyone tell why? Also, in the current code I found a strange check I couldn't make sense of (`equiv.js Line 90 - arrays check`):

    // b could be an object literal here
    if ( QUnit.objectType( b ) !== "array" ) {
         return false;
    }

It looks to me that `b` would always be an array. This looks redundant.

**Comment by leobalter** [comment]
The CI is ok, the error there is just a known issue with browserstack.

I still need to find more available time to check the CLA issue.
