### ISSUE TITLE
QUnit DeepEqual using two strings

### ISSUE THREAD

**Issue by joeJazdzewski** [jquery/qunit#895]
I was testing some code using qunit my test kept failing so I tested 

    var str = new String("hey there");
    var s = new String("hey there");
    assert.deepEqual(s, str);
    assert.equal(s, str);

both equal trys failed

**Comment by platinumazure** [comment]
`new String` will result in the types actually being objects, not strings. So I would expect `assert.equal` to fail since `str == s` is false. As for `deepEqual` failing, my guess is your implementation stores an ID (or hash code, or...) within the string object, and so `deepEqual` will fail as well when it compares property-to-property.

Try using string literals rather than objects. For example, if you have a function that returns `"hey there"`, the correct assertion would be:

```js
var result = myHeyThereFunction();
assert.equal(result, "hey there", "Got 'hey there' back!");
// Or better:
assert.strictEqual(result, "hey there", "Got 'hey there' back!");
```

**Comment by leobalter** [comment]
I can't see a good reason to instantiate string objects using the new String form. If you really need to stick with it, keep in mind different object instances will not pass on the simple equal comparison, if what you want to compare is the value, you can catch its value instead.

```js
var s = new String( "hey there" )
s; // a String typed object, with a collection of each character
typeof s; // "object"

s.toString(); // the value of this object when converted to a simple regular string.
typeof s.toString(); // "string"
```

Both in `==` (equivalent to `assert.equal`) and `===` (equivalent to `assert.strictEqual`) you will only have `true` returning if both objects share the same reference.

What we can still check is the `deepEqual` assertion, as it should check for the object props.

```js
  assert.deepEqual(new String("foo"), new String("foo")); // fails
  assert.deepEqual(new String(), new String()); // fails
  assert.deepEqual(new Object(), new Object()); // pass
  assert.deepEqual({foo: "bar"}, {foo: "bar"}); // pass
```
