### ISSUE TITLE
Module picker is broken

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#988]
The multi-select picker introduced in 0780127c7f64eed14596afb0b3873b0dc6a389ef provides no mechanism for committing a selection, and suffers some on styling and accessibility. I'd like to fix it before 2.0.

**Comment by trentmwillis** [comment]
Styling seemed okay to me, but I did note some other issues as you did as well:

* Accessibility could be improved
* Shouldn't have to hit "go" in order to commit a selection (not intuitive)
* After closing the dropdown, there should be some indication of what has been selected
* After closing the dropdown, the previous search/filter should clear
* There should be some indication that the thing is a dropdown and not just a text input
* The labels for the options should be block-level so that users can click anywhere in the row to select an item
* Since "All modules" doesn't switch all the checkboxes to "checked", it should probably say "Clear all" or something similar
